version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 EIS_test_task.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  celery:
    build: .
    command: celery -A EIS_test_task worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A EIS_test_task flower --port=5555 --basic_auth=user:password
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - celery


volumes:
  postgres_data:
