# Generated by Django 5.1.1 on 2024-09-20 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTariffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за квадратный метр')),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTariffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за кубометр воды')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер квартиры')),
                ('apartment_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь квартиры')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkh_app.housemodel')),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to='jkh_app.apartmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SerialWaterMeterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Номер счетчика')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Счетчик', to='jkh_app.watermetermodel')),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(default=django.utils.timezone.now)),
                ('water_meter_value', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Общий подсчет показателей')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkh_app.serialwatermetermodel', verbose_name='Серийный номер счетчика')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата расчета')),
                ('total_area_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за содержание общего имущества')),
                ('total_water_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная стоимость')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkh_app.apartmentmodel')),
                ('area_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkh_app.areatariffmodel')),
                ('water_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkh_app.watertariffmodel')),
            ],
        ),
    ]
